language: cpp
compiler:
    - gcc
sudo: false
addons:
    apt:
        packages:
        - lib32stdc++6
        - lib32z1-dev
        - libc6-dev-i386
        - linux-libc-dev
        
        - lib32gcc-5-dev
        - libgcc-5-dev
        - g++-5-multilib
        - gcc-5-multilib
        - g++-5
        - gcc-5
        
        - realpath
        sources:
            - ubuntu-toolchain-r-test
    cache:
        directories:
            - ../mysql-5.0
    
install:
    - git clone https://github.com/alliedmodders/sourcemod.git --recursive -b 1.8-dev $TRAVIS_BUILD_DIR/../sourcemod
    - cd $TRAVIS_BUILD_DIR/../
    - wget https://raw.githubusercontent.com/alliedmodders/sourcemod/master/tools/checkout-deps.sh && chmod +x checkout-deps.sh
    - ./checkout-deps.sh
    #fixing some dumb issues {
    - mkdir -p $TRAVIS_BUILD_DIR/../include/asm
    - cp -r /usr/include/asm-generic/* $TRAVIS_BUILD_DIR/../include/asm/
    #}
    
script:
    - mkdir $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
    #again, fixing some dumb issues {
    - export CPLUS_INCLUDE_PATH=$(realpath $TRAVIS_BUILD_DIR/../include)
    #}
    - CXX=g++-5 CC=gcc-5 python ../configure.py --enable-optimize -s present
    - ambuild
    
before_deploy: 
    - COMM_NUMBER=$(git rev-list --count HEAD)
    - FILE="think_hooks-n$COMM_NUMBER-linux.zip"
    - cd $TRAVIS_BUILD_DIR/build/package/addons/sourcemod
    - zip -r $TRAVIS_BUILD_DIR/$FILE ./extensions/ ./scripting/
    - cd $TRAVIS_BUILD_DIR

deploy:
    provider: releases
    api_key:
        secure: ARHk8NuMUPinO/ZAbnEancK+WNS7p9/Vxs2kTdKpgFdBbS8kuHUYi7sKfmOhk615jw8xP959KcS7rnAXlEFlXG7g9uWz/Xf6+6mRUM5UOySFqbADsbkck8br0yKxaUDtMb2vUlzCwfpqg+9j/w8YG4PaepyAIpxuYptimdZlhbGgAqqqEbIc2kwchco95MDfdxZtNguZGOst/JptZjgxrnFDwiqiOREYqfqI9wIFd7WwguRfz51YtiYeCEdFNpl99BVo+PSxb5IttSkHtAKr6DK1P7CUk7/cBLhW4JKwwzO590ikfQJNDBcNPvyoaVaIHOcMVsSZAmOOK3kRtViLW9repP4NbPLhcwBJZRi6DgU02lVVl06SP6KaW+xYdO4pelPJw10fHGzq+PXb4nwwe30ucbRUNTvGpWNW7tk7dNI7nmWQbvucqv9VFeTkz9fBRIdnhvWQ0bnpkCf5sTZYHxk5Ej7wbGcj2GyB+aypwtR3XqvOYZYrFcNOHNDjsfQmB9my1YC7ZcRoZ/9GI8wlT2xikJoRH5QkBVNNmBvFgo2WWFJbrlhVynJvnt5SHuYalromsH3rD0mC1Z21rBHZ6HEIYAnQwEG2hfguIUe8yhFrC85EQJRc4rW6T4n91viSNeUr4kJdWhbrfJSJUAM9p4DPNFTZvWdBdMNn07R1w+8=
    file: $FILE
    on:
        repo: servadestroya/think_hooks
        tags: true
        branch: master
