language: cpp
compiler:
    - gcc
#sudo: false
addons:
    apt:
        packages:
        - lib32stdc++6
        - lib32z1-dev
        - libc6-dev-i386
        - linux-libc-dev

        - lib32z1 
        - libc6-i386
        
        - lib32gcc-5-dev
        - libgcc-5-dev
        - g++-5-multilib
        - gcc-5-multilib
        - g++-5
        - gcc-5
        sources:
            - ubuntu-toolchain-r-test
    cache:
        directories:
            - ../mysql-5.0
env:
    global:
    - LLVM_ARCHIVE_URI=http://sourcemod.net/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
    
before_install:
    #- wget -nc $LLVM_ARCHIVE_URI -O $HOME/clang+llvm.tar.xz
    #- mkdir -p $HOME/clang+llvm
    #- tar -xf $HOME/clang+llvm.tar.xz -C $HOME/clang+llvm --strip-components 1
    #- export PATH=$HOME/clang+llvm/bin:$PATH
    
install:
    #- git clone https://github.com/alliedmodders/ambuild.git $TRAVIS_BUILD_DIR/../ambuild
    #  && cd $TRAVIS_BUILD_DIR/../ambuild && python setup.py build && sudo python setup.py
    #  install
    #- git clone https://github.com/alliedmodders/metamod-source.git -b 1.10-dev $TRAVIS_BUILD_DIR/../metamod-source
    - git clone https://github.com/alliedmodders/sourcemod.git --recursive -b 1.8-dev
      $TRAVIS_BUILD_DIR/../sourcemod
    - cd $TRAVIS_BUILD_DIR/../
    - wget https://raw.githubusercontent.com/alliedmodders/sourcemod/master/tools/checkout-deps.sh && chmod +x checkout-deps.sh
    - ./checkout-deps.sh
    - sudo ln -s /usr/include/asm-generic /usr/include/asm
    
script:
    - mkdir $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
    - CXX=g++-5 CC=gcc-5 python ../configure.py --enable-optimize
    - ambuild
